### ISSUE TITLE
Crashes on dedicated server without crash report

### ISSUE THREAD

**Issue by RDKRACZ** [charlyb01/xp_storage#7]
latest.log below

```
[10:25:58] [main/INFO]: [FabricLoader] Loading 47 mods: fabric-screen-handler-api-v1@1.1.0+6a2618f53a, minecraft@1.16.4, fabric-renderer-api-v1@0.3.3+6a2618f53a, fabric-networking-blockentity-v0@0.2.7+a03e98793a, fabric-keybindings-v0@0.2.0+6a2618f53a, xpstorage@1.2+1.16.4, fabric-command-api-v1@1.0.9+6a2618f53a, fabricloader@0.10.8, fabric-tool-attribute-api-v1@1.2.5+6a2618f53a, fabric-renderer-indigo@0.4.3+6a2618f53a, fabric-structure-api-v1@1.1.1+f1d8af063a, fabric-containers-v0@0.1.9+a03e98793a, fabric-object-builder-api-v1@1.9.2+6a2618f53a, fabric-dimensions-v1@2.0.1+9a6c75813a, fabric-item-api-v1@1.2.0+6a2618f53a, fabric-events-interaction-v0@0.4.1+6a2618f53a, fabric-crash-report-info-v1@0.1.2+b7f9825d3a, fabric-game-rule-api-v1@1.0.3+a4467d2a3a, fabric-api-base@0.2.0+ab87788d3a, fabric-rendering-v0@1.1.1+6a2618f53a, fabric-rendering-v1@1.4.0+6a2618f53a, fabric-key-binding-api-v1@1.0.1+730711c63a, fabric-rendering-data-attachment-v1@0.1.4+6a2618f53a, fabric-resource-loader-v0@0.3.2+1944f3e03a, cardinal-components-item@2.7.9, fabric-textures-v0@1.0.5+6a2618f53a, fabric-content-registries-v0@0.2.0+e77439c73a, fabric-tag-extensions-v0@1.1.0+e77439c73a, fabric-rendering-fluids-v1@0.1.12+6a2618f53a, fabric-biome-api-v1@3.1.0+2e23b97c3a, cardinal-components-entity@2.7.9, fabric-registry-sync-v0@0.7.2+a03e98793a, fabric-commands-v0@0.2.0+6a2618f53a, cardinal-components-base@2.7.9, fabric-blockrenderlayer-v1@1.1.4+6a2618f53a, fabric-lifecycle-events-v1@1.2.0+ffb68a873a, fabric-mining-levels-v0@0.1.2+6a2618f53a, fabric-renderer-registries-v1@2.2.0+6a2618f53a, fabric-networking-api-v1@1.0.0+4358fbc63a, fabric-loot-tables-v1@1.0.1+6a2618f53a, fabric-events-lifecycle-v0@0.2.0+6a2618f53a, fabric@0.28.0+1.16, fabric-particles-v1@0.2.2+6a2618f53a, fabric-models-v0@0.1.1+6a2618f53a, fabric-item-groups-v0@0.2.1+6a2618f53a, fabric-object-builders-v0@0.7.1+6a2618f53a, fabric-networking-v0@0.3.0+a03e98793a
[10:25:59] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/k0rr/Downloads/SerVeR/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[10:26:03] [main/WARN]: Error loading class: net/minecraft/class_1836 (java.lang.ClassNotFoundException: net/minecraft/class_1836)
[10:26:03] [main/FATAL]: Mixin apply failed xpstorage.mixins.json:XpBottleItemMixin -> net.minecraft.class_1779: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> xpstorage.mixins.json:XpBottleItemMixin -> Apply Methods -> (Lnet/minecraft/class_1799;Lnet/minecraft/class_1937;Ljava/util/List;Lnet/minecraft/class_1836;)V:method_7851 -> Transform Descriptor -> desc=Lnet/minecraft/class_1836;]
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> xpstorage.mixins.json:XpBottleItemMixin -> Apply Methods -> (Lnet/minecraft/class_1799;Lnet/minecraft/class_1937;Ljava/util/List;Lnet/minecraft/class_1836;)V:method_7851 -> Transform Descriptor -> desc=Lnet/minecraft/class_1836;]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:490) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:523) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:509) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:381) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
	at net.minecraft.class_2378.method_10234(class_2378.java:158) ~[intermediary-server.jar:?]
	at net.minecraft.class_2378.method_29110(class_2378.java:246) ~[intermediary-server.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) [?:1.8.0_275]
	at net.minecraft.class_2378.<clinit>(class_2378.java:245) [intermediary-server.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:42) [intermediary-server.jar:?]
	at net.minecraft.server.Main.main(Main.java:87) [intermediary-server.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27) [fabric-server-launch.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]
Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: net.minecraft.class_1836
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:949) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:909) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethodDescriptor(MixinTargetContext.java:964) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformDescriptor(MixinTargetContext.java:865) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:447) ~[fabric-server-launch.jar:?]
	... 33 more
```

**Comment by charlyb01** [comment]
Oh okay, I'll check it out tomorrow morning! Thanks for reporting

**Comment by charlyb01** [comment]
Thanks again for reporting it quickly! Hope you'll enjoy the new feature of the update =)
